manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.2.0
      import:
        name-allowlist:
          - cmsis              # Core ARM Cortex headers (required by both)
          - hal_stm32          # Vendor HAL for the STM32
          - hal_nordic         # Vendor HAL for the nRF52833
          - segger             # Standard debug libs
  self:
    path: coral-cubed-flight