## System
# General/Device
CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_500PPM=y
CONFIG_MAIN_STACK_SIZE=2048

# Kernel/Concurrency
CONFIG_EVENTS=y
CONFIG_UART_INTERRUPT_DRIVEN=y

## Debugging

# Turn OFF RTT
CONFIG_USE_SEGGER_RTT=n
CONFIG_RTT_CONSOLE=n

# Turn OFF Console Subsystems
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_PRINTK=n
CONFIG_BOOT_BANNER=n
CONFIG_LOG=n

## Communications

# UART
CONFIG_UART_USE_RUNTIME_CONFIGURE=y
CONFIG_UART_LINE_CTRL=y
# USB Stack
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="Coral COM Board"
CONFIG_USB_DEVICE_VID=0x2FE3
CONFIG_USB_DEVICE_PID=0x0100
CONFIG_USB_CDC_ACM=y    

# Radio IEE Stack
CONFIG_NETWORKING=y
CONFIG_NET_L2_IEEE802154=y
CONFIG_NET_L2_IEEE802154_RADIO_DFLT_TX_POWER=-12
CONFIG_IEEE802154_NRF5=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_PACKET=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
## System
# General/Device
CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_500PPM=y
CONFIG_MAIN_STACK_SIZE=2048

# Kernel/Concurrency
CONFIG_EVENTS=y
CONFIG_UART_INTERRUPT_DRIVEN=y

## Debugging

# Turn OFF RTT
CONFIG_USE_SEGGER_RTT=n
CONFIG_RTT_CONSOLE=n

# Turn OFF Console Subsystems
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_PRINTK=n
CONFIG_BOOT_BANNER=n
CONFIG_LOG=n

## Communications

# UART
CONFIG_UART_USE_RUNTIME_CONFIGURE=y
CONFIG_UART_LINE_CTRL=y
# USB Stack
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="Coral COM Board"
CONFIG_USB_DEVICE_VID=0x2FE3
CONFIG_USB_DEVICE_PID=0x0100
CONFIG_USB_CDC_ACM=y    

# Radio IEE Stack
CONFIG_NETWORKING=y
CONFIG_NET_L2_IEEE802154=y
CONFIG_NET_L2_IEEE802154_RADIO_DFLT_TX_POWER=-12
CONFIG_IEEE802154_NRF5=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_PACKET=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_L2_IEEE802154_RADIO_CSMA_CA=n