[platformio]
default_envs = coral_stm32_flash_demo

[env]
platform = ststm32
framework = zephyr
board = coral_stm32
platform_packages =
  platformio/framework-zephyr@~3.40300.0
debug_tool = stlink
upload_protocol = stlink
monitor_speed = 115200
board_build.zephyr.variant = coral_stm32
board_build.zephyr.cmake_extra_args =
  -DBOARD_ROOT="${PROJECT_DIR}/../CDH"
  -DCONF_FILE=prj.conf

[env:coral_stm32_flash_demo]
extends = env