# USB CDC ACM console (debug printk only)
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y
CONFIG_UART_CONSOLE=n

# Flash
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_JESD216_API=y

# UART interrupt driven (for UART1 TAB receive)
CONFIG_UART_INTERRUPT_DRIVEN=y

# CRC
CONFIG_CRC=y
